<!-- Open Graph Data -->
<meta property="og:site_name" content="The name of the website." />
<meta property="og:title" content="The title of your object as it should appear within the graph, e.g., 'The Rock'" />
<meta property="og:description" content="The description of the current page." />
<meta property="og:type" content="The type of your object, e.g., 'video.movie'. Depending on the type you specify, other properties may also be required." />
<meta property="og:url" content=" The canonical URL of your object that will be used as its permanent ID in the graph, e.g., 'http://www.imdb.com/title/tt0117500/'" />
<meta property="og:image" content="An image URL which should represent your object within the graph." />
<!-- /Open Graph Data -->