<!--[if IE 9]>
<script src="/static/js/shim.js"></script>
<![endif]-->
<script src="/static/js/initial.js" data-inline></script>

<script>
    DEBUG = {
        A11Y: true, // load a11y helpers/warnings
        BASELINE: true, // show baseline toggle
        COUNT: true, // count CSS selectors/rules
        CSS: true // load debug CSS (baseline, ...)
    }
</script>
<script src="/static/js/debug.js"></script>